### ISSUE TITLE
Support for limiting the number of CDF resources in the list endpoint

### ISSUE THREAD

**Issue by evertoncolling** [cognitedata/cdf-sdk-java#189]
I'm trying the Java SDK and was unable to limit the number of results in the list query.

I understood that the limit should be specified in the `.withRootParameter` method, but the client is not limiting the items in the result. The screenshot below shows an example, where I'm trying to retrieve only 10 assets, but the SDK returns all assets.
<img width="455" alt="image" src="https://user-images.githubusercontent.com/33816483/179761345-c8d3269c-318f-429e-93c6-328fc06f9313.png">

For comparison, here is what I'm getting using the Python SDK (authenticated to the same CDF project):
<img width="401" alt="image" src="https://user-images.githubusercontent.com/33816483/179762747-2170620d-bf69-4535-9dee-04f545c25490.png">

Is this a bug, or am I using the wrong syntax here?

**Comment by kjetilh33** [comment]
Hi Everton,

You are using the correct syntax for setting the API parameter "limit". But, the behavior may not be what you expect. "limit" defines the max batch size on the responses from the CDF API. But, the SDK does a few things under the hood in order to optimize for iteration/list performance:
1) The SDK performs 8 parallel requests to CDF. Each of those 8 streams produce a response from CDF with "limit" number of items. The result batch returned to the client is the union of the 8 streams. I.e. in your case, the client receives a "superbatch" of 8 * 10 = 80 items.
2) ".forEachRemaining" performs an iteration so you keep on paging through the results from CDF. I.e. your code effectively downloads the entire results set from CDF (albeit in a rather inefficient manner by using a low batch size of 10). 

If you want to limit the number of results from a "list" operation, you can:
1) Do not iterate through the entire results set (i.e. ".forEachRemaining()"), but just read the first results batch and then dispose of the iterator. Read the top n items from this batch.
2) Set the limit parameter + set parallelization to "1" (via the ClientConfig object) + only read the first result batch (i.e. no iteration). That should give your a results batch of max "limit" size.

Out of curiosity: what is your scenario? Up until now I have mostly seen "list()" being used for downloading an entire results set (possibly given a set of filters) while "retrieve()" give you more control over which items you download.

**Comment by evertoncolling** [comment]
Hi Kjetil,

thanks for the explanation on the inner workings of the SDK, it all makes sense now. 

When it comes to the scenario, I was just experimenting with the SDK, exploring datatypes and it's properties from Java interactively and that's why I was looking to retrieve just a small number of objects using `list()` with a `limit`. On a real autonomous application I would be most likely interested into downloading the entire result set (based on a set of filters)  as you mentioned.

Since this is not a bug, I'm closing the issue.
